import mongoose, { Schema } from "mongoose";

// In this password is not needed as it will be automatically generated by system, aslo user reaches this syaye only when he has confirmed OTP
// also recapta will be added

const pendingUserSchema = new mongoose.Schema(
  {
    _id: {
      type: Schema.Types.ObjectId,
      required: true,
      default: () => new mongoose.Types.ObjectId(),
    },
    name: { type: String, required: true },
    email: { type: String, required: true, unique: true },
    applier_type: { type: String, required: true, default: "none" },
    logo_url: { type: String, required: true, default: "none" },
    status: {
      type: String,
      required: true,
      enum: ["verified", "unverified"],
      default: "unverified",
    },
    about: { type: String, required: true, default: "none" },
    website: { type: String, required: true, default: "none" },
    designation: { type: String, required: true, default: "none" },
    reason: { type: String, required: true, default: "none" },
    schema_complete: { type: Boolean, required: true, default: false },
    date_of_request: { type: String, required: true, default: Date.now },
  },
  {
    collection: "pendingusers",
  }
);

export default mongoose.models.PendingUser ||
  mongoose.model("PendingUser", pendingUserSchema);
